version: '3.8'
services:
  chat-server:
    build: ./server
    env_file:
      - ./zphilo/.env
    ports:
      - "3000:3000"
    volumes:
      - ./server/ai:/usr/src/app/ai
      - ./zphilo:/usr/src/zphilo

  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - ./zphilo/.env
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
    volumes:
      - ./n8n_data:/home/node/.n8n